services:
  - type: web
    name: mercurios-connect-app
    env: node
    region: frankfurt
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SCOPES
        value: write_products,read_orders,read_customers,write_customers
      - key: SHOPIFY_APP_URL
        sync: false
      - key: MONGODB_URI
        sync: false
