# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "74289b85e3512cc12a7f23dab1af895d"
name = "MercuriosAiHyperlinked"
application_url = "https://mercurios-connect-app.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "orders/paid" ]
  uri = "/webhooks/orders/paid"

  [[webhooks.subscriptions]]
  topics = [ "customers/create", "customers/update" ]
  uri = "/webhooks/customers/sync"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders,read_customers,write_customers"

[auth]
redirect_urls = [
  "https://mercurios-connect-app.onrender.com/auth/callback",
  "https://mercurios-connect-app.onrender.com/auth/shopify/callback",
  "https://mercurios-connect-app.onrender.com/api/auth/callback"
]
